[build]
  command = "cd backend && npm install && cd ../frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend"
  node_bundler = "esbuild"

# THIS MUST BE FIRST
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/api/:splat"
  status = 200

# THIS MUST BE SECOND
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200